import type { Team } from './definitions';
import usaFlag from '../assets/Flag_of_the_United_States.svg';
import canadaFlag from '../assets/Flag_of_Canada.svg';
import swedenFlag from '../assets/Flag_of_Sweden.svg';
import finlandFlag from '../assets/Flag_of_Finland.svg';

export const teamUSA: Team = {
  forwards: [
    {
      number: 7,
      name: 'Brady Tkachuk',
      born: '1999',
      league: 'NHL',
      team: 'Ottawa Senators',
      height: 193,
      weight: 96,
      shoots: 'L',
      position: 'LW',
      games_played: 37,
      goals: 14,
      assists: 23,
      points: 37,
      plus_minus: '-4',
      time_on_ice_per_game_played: '17:04',
    },
    {
      number: 9,
      name: 'Jack Eichel',
      born: '1996',
      league: 'NHL',
      team: 'Vegas Golden Knights',
      height: 188,
      weight: 93,
      shoots: 'R',
      position: 'C',
      games_played: 50,
      goals: 21,
      assists: 47,
      points: 68,
      plus_minus: '+18',
      time_on_ice_per_game_played: '21:17',
    },
    {
      number: 10,
      name: 'J.T. Miller',
      born: '1993',
      league: 'NHL',
      team: 'New York Rangers',
      height: 186,
      weight: 99,
      shoots: 'L',
      position: 'C',
      games_played: 48,
      goals: 14,
      assists: 22,
      points: 36,
      plus_minus: '-22',
      time_on_ice_per_game_played: '20:40',
    },
    {
      number: 12,
      name: 'Matt Boldy',
      born: '2001',
      league: 'NHL',
      team: 'Minnesota Wild',
      height: 188,
      weight: 91,
      shoots: 'L',
      position: 'LW',
      games_played: 54,
      goals: 32,
      assists: 20,
      points: 62,
      plus_minus: '+14',
      time_on_ice_per_game_played: '20:51',
    },
    {
      number: 16,
      name: 'Vincent Trocheck',
      born: '1993',
      league: 'NHL',
      team: 'New York Rangers',
      height: 180,
      weight: 85,
      shoots: 'R',
      position: 'C',
      games_played: 43,
      goals: 12,
      assists: 24,
      points: 36,
      plus_minus: '-16',
      time_on_ice_per_game_played: '20:57',
    },
    {
      number: 19,
      name: 'Matthew Tkachuk',
      born: '1997',
      league: 'NHL',
      team: 'Florida Panthers',
      height: 188,
      weight: 91,
      shoots: 'L',
      position: 'LW',
      games_played: 10,
      goals: 3,
      assists: 5,
      points: 8,
      plus_minus: '-7',
      time_on_ice_per_game_played: '18:41',
    },
    {
      number: 21,
      name: 'Dylan Larkin',
      born: '1996',
      league: 'NHL',
      team: 'Detroit Red Wings',
      height: 185,
      weight: 93,
      shoots: 'L',
      position: 'C',
      games_played: 58,
      goals: 26,
      assists: 25,
      points: 51,
      plus_minus: '+8',
      time_on_ice_per_game_played: '20:18',
    },
    {
      number: 29,
      name: 'Brock Nelson',
      born: '1991',
      league: 'NHL',
      team: 'Colorado Avalanche',
      height: 193,
      weight: 93,
      shoots: 'L',
      position: 'C',
      games_played: 55,
      goals: 29,
      assists: 20,
      points: 49,
      plus_minus: '+7',
      time_on_ice_per_game_played: '19:14',
    },
    {
      number: 34,
      name: 'Auston Matthews',
      born: '1997',
      league: 'NHL',
      team: 'Toronto Maple Leafs',
      height: 191,
      weight: 98,
      shoots: 'L',
      position: 'C',
      games_played: 51,
      goals: 26,
      assists: 22,
      points: 48,
      plus_minus: '+4',
      time_on_ice_per_game_played: '20:49',
    },
    {
      number: 59,
      name: 'Jake Guentzel',
      born: '1994',
      league: 'NHL',
      team: 'Tampa Bay Lightning',
      height: 180,
      weight: 80,
      shoots: 'L',
      position: 'C',
      games_played: 55,
      goals: 26,
      assists: 34,
      points: 60,
      plus_minus: '+13',
      time_on_ice_per_game_played: '20:29',
    },
    {
      number: 72,
      name: 'Tage Thompson',
      born: '1997',
      league: 'NHL',
      team: 'Buffalo Sabres',
      height: 197,
      weight: 100,
      shoots: 'R',
      position: 'C',
      games_played: 57,
      goals: 30,
      assists: 29,
      points: 59,
      plus_minus: '-8',
      time_on_ice_per_game_played: '19:09',
    },
    {
      number: 81,
      name: 'Kyle Connor',
      born: '1996',
      league: 'NHL',
      team: 'Winnipeg Jets',
      height: 185,
      weight: 83,
      shoots: 'L',
      position: 'LW',
      games_played: 56,
      goals: 25,
      assists: 39,
      points: 64,
      plus_minus: '-3',
      time_on_ice_per_game_played: '21:08',
    },
    {
      number: 86,
      name: 'Jack Hughes',
      born: '2001',
      league: 'NHL',
      team: 'New Jersey Devils',
      height: 180,
      weight: 80,
      shoots: 'L',
      position: 'C',
      games_played: 36,
      goals: 12,
      assists: 24,
      points: 36,
      plus_minus: '-6',
      time_on_ice_per_game_played: '20:57',
    },
    {
      number: 91,
      name: 'Clayton Keller',
      born: '1998',
      league: 'NHL',
      team: 'Utah Mammoth',
      height: 178,
      weight: 79,
      shoots: 'L',
      position: 'RW',
      games_played: 57,
      goals: 17,
      assists: 37,
      points: 54,
      plus_minus: '+22',
      time_on_ice_per_game_played: '19:01',
    },
  ],
  defensemen: [
    {
      number: 2,
      name: 'Jackson LaCombe',
      born: '2001',
      league: 'NHL',
      team: 'Anaheim Ducks',
      height: 188,
      weight: 94,
      shoots: 'L',
      games_played: 56,
      goals: 6,
      assists: 31,
      points: 37,
      plus_minus: '-5',
      time_on_ice_per_game_played: '24:30',
    },
    {
      number: 8,
      name: 'Zach Werenski',
      born: '1997',
      league: 'NHL',
      team: 'Columbus Blue Jackets',
      height: 188,
      weight: 97,
      shoots: 'L',
      games_played: 52,
      goals: 20,
      assists: 42,
      points: 62,
      plus_minus: '+8',
      time_on_ice_per_game_played: '26:22',
    },
    {
      number: 14,
      name: 'Brock Faber',
      born: '2002',
      league: 'NHL',
      team: 'Minnesota Wild',
      height: 185,
      weight: 91,
      shoots: 'R',
      games_played: 58,
      goals: 13,
      assists: 24,
      points: 37,
      plus_minus: '+19',
      time_on_ice_per_game_played: '24:59',
    },
    {
      number: 15,
      name: 'Noah Hanifin',
      born: '1997',
      league: 'NHL',
      team: 'Vegas Golden Knights',
      height: 191,
      weight: 98,
      shoots: 'L',
      games_played: 47,
      goals: 2,
      assists: 18,
      points: 20,
      plus_minus: '-1',
      time_on_ice_per_game_played: '23:26',
    },
    {
      number: 25,
      name: 'Charlie McAvoy',
      born: '1997',
      league: 'NHL',
      team: 'Boston Bruins',
      height: 185,
      weight: 96,
      shoots: 'R',
      games_played: 45,
      goals: 4,
      assists: 35,
      points: 39,
      plus_minus: '+5',
      time_on_ice_per_game_played: '24:10',
    },
    {
      number: 43,
      name: 'Quinn Hughes',
      born: '1999',
      league: 'NHL',
      team: 'Minnesota Wild',
      height: 178,
      weight: 82,
      shoots: 'L',
      games_played: 52,
      goals: 5,
      assists: 52,
      points: 57,
      plus_minus: '+9',
      time_on_ice_per_game_played: '28:18',
    },
    {
      number: 74,
      name: 'Jaccob Slavin',
      born: '1994',
      league: 'NHL',
      team: 'Carolina Hurricanes',
      height: 191,
      weight: 94,
      shoots: 'L',
      games_played: 17,
      goals: 0,
      assists: 3,
      points: 3,
      plus_minus: '+9',
      time_on_ice_per_game_played: '20:12',
    },
    {
      number: 85,
      name: 'Jake Sanderson',
      born: '2002',
      league: 'NHL',
      team: 'Ottawa Senators',
      height: 188,
      weight: 92,
      shoots: 'L',
      games_played: 57,
      goals: 11,
      assists: 35,
      points: 46,
      plus_minus: '+7',
      time_on_ice_per_game_played: '25:01',
    },
  ],
  goalies: [
    {
      number: 1,
      name: 'Jeremy Swayman',
      born: '1998',
      league: 'NHL',
      team: 'Boston Bruins',
      height: 191,
      weight: 88,
      games_played: 38,
      wins: 22,
      losses: 12,
      overtime_losses: 3,
      goals_against_average: 2.92,
      save_percentage: 0.903,
      time_on_ice: '2242:38',
    },
    {
      number: 30,
      name: 'Jake Oettinger',
      born: '1998',
      league: 'NHL',
      team: 'Dallas Stars',
      height: 198,
      weight: 102,
      games_played: 37,
      wins: 23,
      losses: 10,
      overtime_losses: 4,
      goals_against_average: 2.73,
      save_percentage: 0.897,
      time_on_ice: '2195:10',
    },
    {
      number: 37,
      name: 'Connor Hellebuyck',
      born: '1993',
      league: 'NHL',
      team: 'Winnipeg Jets',
      height: 193,
      weight: 94,
      games_played: 36,
      wins: 13,
      losses: 16,
      overtime_losses: 7,
      goals_against_average: 2.79,
      save_percentage: 0.9,
      time_on_ice: '2152:01',
    },
  ],
};

export const teamCanada: Team = {
  forwards: [
    {
      number: 9,
      name: 'Sam Bennett',
      born: '1996',
      league: 'NHL',
      team: 'Florida Panthers',
      height: 185,
      weight: 88,
      shoots: 'L',
      position: 'C',
      games_played: 57,
      goals: 19,
      assists: 23,
      points: 42,
      plus_minus: '-11',
      time_on_ice_per_game_played: '18:29',
    },
    {
      number: 10,
      name: 'Nick Suzuki',
      born: '1999',
      league: 'NHL',
      team: 'Montréal Canadiens',
      height: 180,
      weight: 94,
      shoots: 'R',
      position: 'C',
      games_played: 57,
      goals: 18,
      assists: 47,
      points: 65,
      plus_minus: '+25',
      time_on_ice_per_game_played: '20:43',
    },
    {
      number: 13,
      name: 'Sam Reinhart',
      born: '1995',
      league: 'NHL',
      team: 'Florida Panthers',
      height: 188,
      weight: 88,
      shoots: 'R',
      position: 'C',
      games_played: 57,
      goals: 27,
      assists: 28,
      points: 55,
      plus_minus: '-16',
      time_on_ice_per_game_played: '21:25',
    },
    {
      number: 14,
      name: 'Bo Horvat',
      born: '1995',
      league: 'NHL',
      team: 'New York Islanders',
      height: 183,
      weight: 101,
      shoots: 'L',
      position: 'C',
      games_played: 44,
      goals: 24,
      assists: 16,
      points: 40,
      plus_minus: '+8',
      time_on_ice_per_game_played: '20:27',
    },
    {
      number: 17,
      name: 'Macklin Celebrini',
      born: '2006',
      league: 'NHL',
      team: 'San Jose Sharks',
      height: 183,
      weight: 86,
      shoots: 'L',
      position: 'C',
      games_played: 55,
      goals: 28,
      assists: 53,
      points: 81,
      plus_minus: '+10',
      time_on_ice_per_game_played: '21:11',
    },
    {
      number: 24,
      name: 'Seth Jarvis',
      born: '2002',
      league: 'NHL',
      team: 'Carolina Hurricanes',
      height: 178,
      weight: 82,
      shoots: 'R',
      position: 'C',
      games_played: 49,
      goals: 25,
      assists: 18,
      points: 43,
      plus_minus: '+10',
      time_on_ice_per_game_played: '19:02',
    },
    {
      number: 29,
      name: 'Nathan MacKinnon',
      born: '1995',
      league: 'NHL',
      team: 'Colorado Avalanche',
      height: 183,
      weight: 91,
      shoots: 'R',
      position: 'C',
      games_played: 55,
      goals: 40,
      assists: 53,
      points: 93,
      plus_minus: '+48',
      time_on_ice_per_game_played: '22:11',
    },
    {
      number: 38,
      name: 'Brandon Hagel',
      born: '1998',
      league: 'NHL',
      team: 'Tampa Bay Lightning',
      height: 187,
      weight: 84,
      shoots: 'L',
      position: 'LW',
      games_played: 50,
      goals: 27,
      assists: 27,
      points: 54,
      plus_minus: '+29',
      time_on_ice_per_game_played: '19:43',
    },
    {
      number: 43,
      name: 'Tom Wilson',
      born: '1994',
      league: 'NHL',
      team: 'Washington Capitals',
      height: 193,
      weight: 100,
      shoots: 'R',
      position: 'RW',
      games_played: 50,
      goals: 23,
      assists: 26,
      points: 49,
      plus_minus: '+20',
      time_on_ice_per_game_played: '19:23',
    },
    {
      number: 61,
      name: 'Mark Stone',
      born: '1992',
      league: 'NHL',
      team: 'Vegas Golden Knights',
      height: 193,
      weight: 96,
      shoots: 'R',
      position: 'RW',
      games_played: 41,
      goals: 21,
      assists: 39,
      points: 60,
      plus_minus: '+18',
      time_on_ice_per_game_played: '19:33',
    },
    {
      number: 63,
      name: 'Brad Marchand',
      born: '1988',
      league: 'NHL',
      team: 'Florida Panthers',
      height: 175,
      weight: 80,
      shoots: 'L',
      position: 'LW',
      games_played: 46,
      goals: 25,
      assists: 25,
      points: 50,
      plus_minus: '-15',
      time_on_ice_per_game_played: '18:12',
    },
    {
      number: 87,
      name: 'Sidney Crosby',
      born: '1987',
      league: 'NHL',
      team: 'Pittsburgh Penguins',
      height: 180,
      weight: 91,
      shoots: 'L',
      position: 'C',
      games_played: 56,
      goals: 27,
      assists: 32,
      points: 59,
      plus_minus: '+1',
      time_on_ice_per_game_played: '19:35',
    },
    {
      number: 93,
      name: 'Mitchell Marner',
      born: '1997',
      league: 'NHL',
      team: 'Vegas Golden Knights',
      height: 183,
      weight: 82,
      shoots: 'R',
      position: 'RW',
      games_played: 57,
      goals: 16,
      assists: 42,
      points: 58,
      plus_minus: '+13',
      time_on_ice_per_game_played: '19:58',
    },
    {
      number: 97,
      name: 'Connor McDavid',
      born: '1997',
      league: 'NHL',
      team: 'Edmonton Oilers',
      height: 185,
      weight: 88,
      shoots: 'L',
      position: 'C',
      games_played: 58,
      goals: 34,
      assists: 62,
      points: 96,
      plus_minus: '+11',
      time_on_ice_per_game_played: '23:07',
    },
  ],
  defensemen: [
    {
      number: 6,
      name: 'Travis Sanheim',
      born: '1996',
      league: 'NHL',
      team: 'Philadelphia Flyers',
      height: 191,
      weight: 82,
      shoots: 'L',
      games_played: 56,
      goals: 6,
      assists: 18,
      points: 24,
      plus_minus: '+2',
      time_on_ice_per_game_played: '24:02',
    },
    {
      number: 7,
      name: 'Devon Toews',
      born: '1994',
      league: 'NHL',
      team: 'Colorado Avalanche',
      height: 185,
      weight: 87,
      shoots: 'L',
      games_played: 42,
      goals: 1,
      assists: 12,
      points: 13,
      plus_minus: '+27',
      time_on_ice_per_game_played: '22:22',
    },
    {
      number: 8,
      name: 'Cale Makar',
      born: '1998',
      league: 'NHL',
      team: 'Colorado Avalanche',
      height: 183,
      weight: 85,
      shoots: 'R',
      games_played: 55,
      goals: 15,
      assists: 42,
      points: 57,
      plus_minus: '+28',
      time_on_ice_per_game_played: '25:05',
    },
    {
      number: 20,
      name: 'Thomas Harley',
      born: '2001',
      league: 'NHL',
      team: 'Dallas Stars',
      height: 191,
      weight: 97,
      shoots: 'L',
      games_played: 45,
      goals: 5,
      assists: 18,
      points: 23,
      plus_minus: '-2',
      time_on_ice_per_game_played: '23:07',
    },
    {
      number: 27,
      name: 'Shea Theodore',
      born: '1995',
      league: 'NHL',
      team: 'Vegas Golden Knights',
      height: 188,
      weight: 89,
      shoots: 'L',
      games_played: 46,
      goals: 7,
      assists: 20,
      points: 27,
      plus_minus: '+13',
      time_on_ice_per_game_played: '23:42',
    },
    {
      number: 44,
      name: 'Josh Morrissey',
      born: '1995',
      league: 'NHL',
      team: 'Winnipeg Jets',
      height: 183,
      weight: 88,
      shoots: 'L',
      games_played: 56,
      goals: 10,
      assists: 32,
      points: 42,
      plus_minus: '+10',
      time_on_ice_per_game_played: '24:37',
    },
    {
      number: 55,
      name: 'Colton Parayko',
      born: '1993',
      league: 'NHL',
      team: 'St. Louis Blues',
      height: 197,
      weight: 104,
      shoots: 'R',
      games_played: 57,
      goals: 1,
      assists: 12,
      points: 13,
      plus_minus: '-15',
      time_on_ice_per_game_played: '22:25',
    },
    {
      number: 89,
      name: 'Drew Doughty',
      born: '1989',
      league: 'NHL',
      team: 'Los Angeles Kings',
      height: 185,
      weight: 95,
      shoots: 'R',
      games_played: 48,
      goals: 3,
      assists: 11,
      points: 14,
      plus_minus: '+1',
      time_on_ice_per_game_played: '22:59',
    },
  ],
  goalies: [
    {
      number: 35,
      name: 'Darcy Kuemper',
      born: '1990',
      league: 'NHL',
      team: 'Los Angeles Kings',
      height: 195,
      weight: 98,
      games_played: 36,
      wins: 14,
      losses: 11,
      overtime_losses: 9,
      goals_against_average: 2.59,
      save_percentage: 0.9,
      time_on_ice: '2081:29',
    },
    {
      number: 48,
      name: 'Logan Thompson',
      born: '1997',
      league: 'NHL',
      team: 'Washington Capitals',
      height: 191,
      weight: 93,
      games_played: 39,
      wins: 19,
      losses: 16,
      overtime_losses: 4,
      goals_against_average: 2.45,
      save_percentage: 0.912,
      time_on_ice: '2304:22',
    },
    {
      number: 50,
      name: 'Jordan Binnington',
      born: '1993',
      league: 'NHL',
      team: 'St. Louis Blues',
      height: 188,
      weight: 78,
      games_played: 32,
      wins: 8,
      losses: 17,
      overtime_losses: 6,
      goals_against_average: 3.65,
      save_percentage: 0.864,
      time_on_ice: '1774:32',
    },
  ],
};

export const teamSweden: Team = {
  forwards: [
    {
      number: 9,
      name: 'Filip Forsberg',
      born: '1994',
      league: 'NHL',
      team: 'Nashville Predators',
      height: 187,
      weight: 93,
      shoots: 'R',
      position: 'LW',
      games_played: 57,
      goals: 24,
      assists: 23,
      points: 47,
      plus_minus: '-5',
      time_on_ice_per_game_played: '18:49',
    },
    {
      number: 10,
      name: 'Alexander Wennberg',
      born: '1994',
      league: 'NHL',
      team: 'San Jose Sharks',
      height: 186,
      weight: 86,
      shoots: 'L',
      position: 'C',
      games_played: 55,
      goals: 10,
      assists: 27,
      points: 37,
      plus_minus: '-16',
      time_on_ice_per_game_played: '20:48',
    },
    {
      number: 14,
      name: 'Joel Eriksson Ek',
      born: '1997',
      league: 'NHL',
      team: 'Minnesota Wild',
      height: 187,
      weight: 94,
      shoots: 'L',
      position: 'C',
      games_played: 52,
      goals: 15,
      assists: 25,
      points: 40,
      plus_minus: '+14',
      time_on_ice_per_game_played: '19:23',
    },
    {
      number: 19,
      name: 'Adrian Kempe',
      born: '1996',
      league: 'NHL',
      team: 'Los Angeles Kings',
      height: 187,
      weight: 91,
      shoots: 'L',
      position: 'RW',
      games_played: 56,
      goals: 20,
      assists: 26,
      points: 46,
      plus_minus: '+8',
      time_on_ice_per_game_played: '19:10',
    },
    {
      number: 23,
      name: 'Lucas Raymond',
      born: '2002',
      league: 'NHL',
      team: 'Detroit Red Wings',
      height: 180,
      weight: 85,
      shoots: 'R',
      position: 'LW',
      games_played: 56,
      goals: 19,
      assists: 41,
      points: 60,
      plus_minus: '+10',
      time_on_ice_per_game_played: '18:34',
    },
    {
      number: 28,
      name: 'Elias Lindholm',
      born: '1994',
      league: 'NHL',
      team: 'Boston Bruins',
      height: 185,
      weight: 91,
      shoots: 'R',
      position: 'C',
      games_played: 44,
      goals: 11,
      assists: 26,
      points: 37,
      plus_minus: '0',
      time_on_ice_per_game_played: '17:29',
    },
    {
      number: 29,
      name: 'Pontus Holmberg',
      born: '1999',
      league: 'NHL',
      team: 'Tampa Bay Lightning',
      height: 183,
      weight: 91,
      shoots: 'L',
      position: 'RW',
      games_played: 48,
      goals: 9,
      assists: 8,
      points: 17,
      plus_minus: '+9',
      time_on_ice_per_game_played: '13:39',
    },
    {
      number: 40,
      name: 'Elias Pettersson',
      born: '1998',
      league: 'NHL',
      team: 'Vancouver Canucks',
      height: 188,
      weight: 84,
      shoots: 'L',
      position: 'C',
      games_played: 49,
      goals: 13,
      assists: 21,
      points: 34,
      plus_minus: '-15',
      time_on_ice_per_game_played: '19:31',
    },
    {
      number: 63,
      name: 'Jesper Bratt',
      born: '1998',
      league: 'NHL',
      team: 'New Jersey Devils',
      height: 179,
      weight: 79,
      shoots: 'L',
      position: 'LW',
      games_played: 57,
      goals: 13,
      assists: 28,
      points: 41,
      plus_minus: '-19',
      time_on_ice_per_game_played: '18:55',
    },
    {
      number: 67,
      name: 'Rickard Rakell',
      born: '1993',
      league: 'NHL',
      team: 'Pittsburgh Penguins',
      height: 186,
      weight: 92,
      shoots: 'R',
      position: 'RW',
      games_played: 35,
      goals: 10,
      assists: 14,
      points: 24,
      plus_minus: '0',
      time_on_ice_per_game_played: '18:59',
    },
    {
      number: 88,
      name: 'William Nylander',
      born: '1996',
      league: 'NHL',
      team: 'Toronto Maple Leafs',
      height: 183,
      weight: 91,
      shoots: 'R',
      position: 'RW',
      games_played: 40,
      goals: 18,
      assists: 34,
      points: 52,
      plus_minus: '+2',
      time_on_ice_per_game_played: '18:33',
    },
    {
      number: 90,
      name: 'Marcus Johansson',
      born: '1990',
      league: 'NHL',
      team: 'Minnesota Wild',
      height: 181,
      weight: 92,
      shoots: 'L',
      position: 'LW',
      games_played: 53,
      goals: 13,
      assists: 24,
      points: 37,
      plus_minus: '+18',
      time_on_ice_per_game_played: '15:50',
    },
    {
      number: 92,
      name: 'Gabriel Landeskog',
      born: '1992',
      league: 'NHL',
      team: 'Colorado Avalanche',
      height: 184,
      weight: 98,
      shoots: 'L',
      position: 'LW',
      games_played: 41,
      goals: 7,
      assists: 15,
      points: 22,
      plus_minus: '+18',
      time_on_ice_per_game_played: '15:51',
    },
    {
      number: 93,
      name: 'Mika Zibanejad',
      born: '1993',
      league: 'NHL',
      team: 'New York Rangers',
      height: 187,
      weight: 92,
      shoots: 'R',
      position: 'C',
      games_played: 56,
      goals: 23,
      assists: 29,
      points: 52,
      plus_minus: '-21',
      time_on_ice_per_game_played: '20:59',
    },
  ],
  defensemen: [
    {
      number: 3,
      name: 'Oliver Ekman Larsson',
      born: '1991',
      league: 'NHL',
      team: 'Toronto Maple Leafs',
      height: 187,
      weight: 86,
      shoots: 'L',
      games_played: 57,
      goals: 8,
      assists: 26,
      points: 34,
      plus_minus: '-1',
      time_on_ice_per_game_played: '20:45',
    },
    {
      number: 4,
      name: 'Rasmus Andersson',
      born: '1996',
      league: 'NHL',
      team: 'Vegas Golden Knights',
      height: 185,
      weight: 92,
      shoots: 'R',
      games_played: 56,
      goals: 11,
      assists: 23,
      points: 34,
      plus_minus: '+6',
      time_on_ice_per_game_played: '23:54',
    },
    {
      number: 6,
      name: 'Philip Broberg',
      born: '2001',
      league: 'NHL',
      team: 'St. Louis Blues',
      height: 191,
      weight: 90,
      shoots: 'L',
      games_played: 56,
      goals: 3,
      assists: 16,
      points: 19,
      plus_minus: '-1',
      time_on_ice_per_game_played: '23:01',
    },
    {
      number: 26,
      name: 'Rasmus Dahlin',
      born: '2000',
      league: 'NHL',
      team: 'Buffalo Sabres',
      height: 190,
      weight: 92,
      shoots: 'L',
      games_played: 53,
      goals: 11,
      assists: 37,
      points: 48,
      plus_minus: '-6',
      time_on_ice_per_game_played: '24:33',
    },
    {
      number: 27,
      name: 'Hampus Lindholm',
      born: '1994',
      league: 'NHL',
      team: 'Boston Bruins',
      height: 193,
      weight: 99,
      shoots: 'L',
      games_played: 43,
      goals: 4,
      assists: 15,
      points: 19,
      plus_minus: '-8',
      time_on_ice_per_game_played: '22:07',
    },
    {
      number: 42,
      name: 'Gustav Forsling',
      born: '1996',
      league: 'NHL',
      team: 'Florida Panthers',
      height: 182,
      weight: 90,
      shoots: 'L',
      games_played: 57,
      goals: 2,
      assists: 19,
      points: 21,
      plus_minus: '-7',
      time_on_ice_per_game_played: '22:41',
    },
    {
      number: 65,
      name: 'Erik Karlsson',
      born: '1990',
      league: 'NHL',
      team: 'Pittsburgh Penguins',
      height: 182,
      weight: 86,
      shoots: 'R',
      games_played: 51,
      goals: 4,
      assists: 31,
      points: 35,
      plus_minus: '+6',
      time_on_ice_per_game_played: '23:40',
    },
    {
      number: 77,
      name: 'Victor Hedman',
      born: '1990',
      league: 'NHL',
      team: 'Tampa Bay Lightning',
      height: 198,
      weight: 111,
      shoots: 'L',
      games_played: 21,
      goals: 0,
      assists: 13,
      points: 13,
      plus_minus: '+2',
      time_on_ice_per_game_played: '20:15',
    },
  ],
  goalies: [
    {
      number: 25,
      name: 'Jacob Markström',
      born: '1990',
      league: 'NHL',
      team: 'New Jersey Devils',
      height: 197,
      weight: 93,
      games_played: 30,
      wins: 15,
      losses: 13,
      overtime_losses: 1,
      goals_against_average: 3.2,
      save_percentage: 0.882,
      time_on_ice: '1704:46',
    },
    {
      number: 30,
      name: 'Jesper Wallstedt',
      born: '2002',
      league: 'NHL',
      team: 'Minnesota Wild',
      height: 191,
      weight: 97,
      games_played: 23,
      wins: 14,
      losses: 5,
      overtime_losses: 4,
      goals_against_average: 2.72,
      save_percentage: 0.914,
      time_on_ice: '1389:18',
    },
    {
      number: 32,
      name: 'Filip Gustavsson',
      born: '1998',
      league: 'NHL',
      team: 'Minnesota Wild',
      height: 188,
      weight: 83,
      games_played: 36,
      wins: 20,
      losses: 9,
      overtime_losses: 6,
      goals_against_average: 2.64,
      save_percentage: 0.907,
      time_on_ice: '2137:36',
    },
  ],
};

export const teamFinland: Team = {
  forwards: [
    {
      number: 15,
      name: 'Anton Lundell',
      born: '2001',
      league: 'NHL',
      team: 'Florida Panthers',
      height: 185,
      weight: 89,
      shoots: 'L',
      position: 'C',
      games_played: 54,
      goals: 16,
      assists: 24,
      points: 40,
      plus_minus: '-9',
      time_on_ice_per_game_played: '19:18',
    },
    {
      number: 20,
      name: 'Sebastian Aho',
      born: '1997',
      league: 'NHL',
      team: 'Carolina Hurricanes',
      height: 183,
      weight: 86,
      shoots: 'L',
      position: 'C',
      games_played: 57,
      goals: 20,
      assists: 37,
      points: 57,
      plus_minus: '+12',
      time_on_ice_per_game_played: '19:46',
    },
    {
      number: 24,
      name: 'Roope Hintz',
      born: '1996',
      league: 'NHL',
      team: 'Dallas Stars',
      height: 191,
      weight: 98,
      shoots: 'L',
      position: 'C',
      games_played: 52,
      goals: 15,
      assists: 29,
      points: 44,
      plus_minus: '+15',
      time_on_ice_per_game_played: '17:27',
    },
    {
      number: 27,
      name: 'Eetu Luostarinen',
      born: '1998',
      league: 'NHL',
      team: ' Florida Panthers',
      height: 190,
      weight: 86,
      shoots: 'L',
      position: 'C',
      games_played: 49,
      goals: 7,
      assists: 17,
      points: 24,
      plus_minus: '+1',
      time_on_ice_per_game_played: '16:49',
    },
    {
      number: 28,
      name: 'Eeli Tolvanen',
      born: '1999',
      league: 'NHL',
      team: 'Seattle Kraken',
      height: 179,
      weight: 87,
      shoots: 'L',
      position: 'RW',
      games_played: 55,
      goals: 11,
      assists: 20,
      points: 31,
      plus_minus: '-8',
      time_on_ice_per_game_played: '16:21',
    },
    {
      number: 40,
      name: 'Joel Armia',
      born: '1993',
      league: 'NHL',
      team: 'Los Angeles Kings',
      height: 191,
      weight: 98,
      shoots: 'R',
      position: 'RW',
      games_played: 51,
      goals: 10,
      assists: 10,
      points: 20,
      plus_minus: '+3',
      time_on_ice_per_game_played: '14:35',
    },
    {
      number: 56,
      name: 'Erik Haula',
      born: '1991',
      league: 'NHL',
      team: 'Nashville Predators',
      height: 183,
      weight: 87,
      shoots: 'L',
      position: 'LW',
      games_played: 57,
      goals: 9,
      assists: 20,
      points: 29,
      plus_minus: '-16',
      time_on_ice_per_game_played: '16:34',
    },
    {
      number: 62,
      name: 'Artturi Lehkonen',
      born: '1995',
      league: 'NHL',
      team: 'Colorado Avalanche',
      height: 181,
      weight: 81,
      shoots: 'L',
      position: 'LW',
      games_played: 55,
      goals: 19,
      assists: 23,
      points: 42,
      plus_minus: '+34',
      time_on_ice_per_game_played: '19:09',
    },
    {
      number: 64,
      name: 'Mikael Granlund',
      born: '1992',
      league: 'NHL',
      team: 'Anaheim Ducks',
      height: 179,
      weight: 88,
      shoots: 'L',
      position: 'C',
      games_played: 38,
      goals: 12,
      assists: 15,
      points: 27,
      plus_minus: '-10',
      time_on_ice_per_game_played: '18:56',
    },
    {
      number: 84,
      name: 'Kaapo Kakko',
      born: '2001',
      league: 'NHL',
      team: 'Seattle Kraken',
      height: 189,
      weight: 98,
      shoots: 'L',
      position: 'RW',
      games_played: 40,
      goals: 6,
      assists: 15,
      points: 21,
      plus_minus: '+7',
      time_on_ice_per_game_played: '14:16',
    },
    {
      number: 86,
      name: 'Teuvo Teräväinen',
      born: '1994',
      league: 'NHL',
      team: 'Chicago Blackhawks',
      height: 180,
      weight: 87,
      shoots: 'L',
      position: 'C',
      games_played: 50,
      goals: 10,
      assists: 13,
      points: 23,
      plus_minus: '-19',
      time_on_ice_per_game_played: '18:06',
    },
    {
      number: 91,
      name: 'Oliver Kapanen',
      born: '2003',
      league: 'NHL',
      team: 'Montréal Canadiens',
      height: 186,
      weight: 88,
      shoots: 'R',
      position: 'C',
      games_played: 57,
      goals: 18,
      assists: 13,
      points: 31,
      plus_minus: '+5',
      time_on_ice_per_game_played: '15:02',
    },
    {
      number: 94,
      name: 'Joel Kiviranta',
      born: '1996',
      league: 'NHL',
      team: 'Colorado Avalanche',
      height: 180,
      weight: 84,
      shoots: 'L',
      position: 'LW',
      games_played: 28,
      goals: 2,
      assists: 5,
      points: 7,
      plus_minus: '0',
      time_on_ice_per_game_played: '10:03',
    },
    {
      number: 96,
      name: 'Mikko Rantanen',
      born: '1996',
      league: 'NHL',
      team: 'Dallas Stars',
      height: 193,
      weight: 103,
      shoots: 'L',
      position: 'RW',
      games_played: 54,
      goals: 20,
      assists: 49,
      points: 69,
      plus_minus: '+2',
      time_on_ice_per_game_played: '20:12',
    },
  ],
  defensemen: [
    {
      number: 3,
      name: 'Olli Määttä',
      born: '1994',
      league: 'NHL',
      team: 'Calgary Flames',
      height: 188,
      weight: 95,
      shoots: 'L',
      games_played: 19,
      goals: 0,
      assists: 1,
      points: 1,
      plus_minus: '-4',
      time_on_ice_per_game_played: '11:55',
    },
    {
      number: 4,
      name: 'Mikko Lehtonen',
      born: '1994',
      league: 'NL',
      team: 'ZSC Lions',
      height: 182,
      weight: 89,
      shoots: 'L',
      games_played: 0,
      goals: 0,
      assists: 0,
      points: 0,
      plus_minus: '0',
      time_on_ice_per_game_played: '00:00',
    },
    {
      number: 10,
      name: 'Henri Jokiharju',
      born: '1999',
      league: 'NHL',
      team: 'Boston Bruins',
      height: 183,
      weight: 93,
      shoots: 'R',
      games_played: 33,
      goals: 0,
      assists: 9,
      points: 9,
      plus_minus: '+3',
      time_on_ice_per_game_played: '17:58',
    },
    {
      number: 23,
      name: 'Esa Lindell',
      born: '1994',
      league: 'NHL',
      team: 'Dallas Stars',
      height: 191,
      weight: 98,
      shoots: 'L',
      games_played: 57,
      goals: 5,
      assists: 17,
      points: 22,
      plus_minus: '+18',
      time_on_ice_per_game_played: '23:45',
    },
    {
      number: 33,
      name: 'Nikolas Matinpalo',
      born: '1998',
      league: 'NHL',
      team: 'Ottawa Senators',
      height: 190,
      weight: 96,
      shoots: 'R',
      games_played: 30,
      goals: 0,
      assists: 4,
      points: 4,
      plus_minus: '0',
      time_on_ice_per_game_played: '15:13',
    },
    {
      number: 41,
      name: 'Miro Heiskanen',
      born: '1999',
      league: 'NHL',
      team: 'Dallas Stars',
      height: 188,
      weight: 89,
      shoots: 'L',
      games_played: 55,
      goals: 7,
      assists: 39,
      points: 46,
      plus_minus: '+7',
      time_on_ice_per_game_played: '25:59',
    },
    {
      number: 55,
      name: 'Rasmus Ristolainen',
      born: '1994',
      league: 'NHL',
      team: 'Philadelphia Flyers',
      height: 192,
      weight: 100,
      shoots: 'R',
      games_played: 19,
      goals: 1,
      assists: 5,
      points: 6,
      plus_minus: '-4',
      time_on_ice_per_game_played: '19:55',
    },
    {
      number: 77,
      name: 'Niko Mikkola',
      born: '1996',
      league: 'NHL',
      team: 'Florida Panthers',
      height: 198,
      weight: 93,
      shoots: 'L',
      games_played: 57,
      goals: 1,
      assists: 8,
      points: 9,
      plus_minus: '+4',
      time_on_ice_per_game_played: '20:18',
    },
  ],
  goalies: [
    {
      number: 32,
      name: 'Kevin Lankinen',
      born: '1995',
      league: 'NHL',
      team: 'Vancouver Canucks',
      height: 187,
      weight: 86,
      games_played: 38,
      wins: 8,
      losses: 22,
      overtime_losses: 5,
      goals_against_average: 3.67,
      save_percentage: 0.875,
      time_on_ice: '2078:01',
    },
    {
      number: 70,
      name: 'Joonas Korpisalo',
      born: '1994',
      league: 'NHL',
      team: 'Boston Bruins',
      height: 193,
      weight: 91,
      games_played: 26,
      wins: 11,
      losses: 9,
      overtime_losses: 4,
      goals_against_average: 3.3,
      save_percentage: 0.891,
      time_on_ice: '1437:16',
    },
    {
      number: 74,
      name: 'Juuse Saros',
      born: '1995',
      league: 'NHL',
      team: 'Nashville Predators',
      height: 179,
      weight: 81,
      games_played: 51,
      wins: 24,
      losses: 19,
      overtime_losses: 7,
      goals_against_average: 3.14,
      save_percentage: 0.894,
      time_on_ice: '2942:58',
    },
  ],
};

export const teams: Record<string, Team> = {
  USA: teamUSA,
  Canada: teamCanada,
  Sweden: teamSweden,
  Finland: teamFinland,
};

export const flags: Record<string, string> = {
  USA: usaFlag,
  Canada: canadaFlag,
  Sweden: swedenFlag,
  Finland: finlandFlag,
};
