import type { Team } from './definitions';

export const teamUSA: Team = {
  forwards: [
    {
      number: 7,
      name: 'Brady Tkachuk',
      born: '9/16/1999',
      league: 'NHL',
      team: 'Ottawa Senators',
      height: 193,
      weight: 96,
      shoots: 'L',
      position: 'LW',
      games_played: 37,
      goals: 14,
      assists: 23,
      points: 37,
      plus_minus: '-4',
      time_on_ice_per_game_played: '17:04',
    },
    {
      number: 9,
      name: 'Jack Eichel',
      born: '10/28/1996',
      league: 'NHL',
      team: 'Vegas Golden Knights',
      height: 188,
      weight: 93,
      shoots: 'R',
      position: 'C',
      games_played: 50,
      goals: 21,
      assists: 47,
      points: 68,
      plus_minus: '+18',
      time_on_ice_per_game_played: '21:17',
    },
    {
      number: 10,
      name: 'J.T. Miller',
      born: '3/14/1993',
      league: 'NHL',
      team: 'New York Rangers',
      height: 186,
      weight: 99,
      shoots: 'L',
      position: 'C',
      games_played: 48,
      goals: 14,
      assists: 22,
      points: 36,
      plus_minus: '-22',
      time_on_ice_per_game_played: '20:40',
    },
    {
      number: 12,
      name: 'Matt Boldy',
      born: '4/5/2001',
      league: 'NHL',
      team: 'Minnesota Wild',
      height: 188,
      weight: 91,
      shoots: 'L',
      position: 'LW',
      games_played: 54,
      goals: 32,
      assists: 20,
      points: 62,
      plus_minus: '+14',
      time_on_ice_per_game_played: '20:51',
    },
    {
      number: 16,
      name: 'Vincent Trocheck',
      born: '7/11/1993',
      league: 'NHL',
      team: 'New York Rangers',
      height: 180,
      weight: 85,
      shoots: 'R',
      position: 'C',
      games_played: 43,
      goals: 12,
      assists: 24,
      points: 36,
      plus_minus: '-16',
      time_on_ice_per_game_played: '20:57',
    },
    {
      number: 19,
      name: 'Matthew Tkachuk',
      born: '12/11/1997',
      league: 'NHL',
      team: 'Florida Panthers',
      height: 188,
      weight: 91,
      shoots: 'L',
      position: 'LW',
      games_played: 10,
      goals: 3,
      assists: 5,
      points: 8,
      plus_minus: '-7',
      time_on_ice_per_game_played: '18:41',
    },
    {
      number: 21,
      name: 'Dylan Larkin',
      born: '7/30/1996',
      league: 'NHL',
      team: 'Detroit Red Wings',
      height: 185,
      weight: 93,
      shoots: 'L',
      position: 'C',
      games_played: 58,
      goals: 26,
      assists: 25,
      points: 51,
      plus_minus: '+8',
      time_on_ice_per_game_played: '20:18',
    },
    {
      number: 29,
      name: 'Brock Nelson',
      born: '10/15/1991',
      league: 'NHL',
      team: 'Colorado Avalanche',
      height: 193,
      weight: 93,
      shoots: 'L',
      position: 'C',
      games_played: 55,
      goals: 29,
      assists: 20,
      points: 49,
      plus_minus: '+7',
      time_on_ice_per_game_played: '19:14',
    },
    {
      number: 34,
      name: 'Auston Matthews',
      born: '9/17/1997',
      league: 'NHL',
      team: 'Toronto Maple Leafs',
      height: 191,
      weight: 98,
      shoots: 'L',
      position: 'C',
      games_played: 51,
      goals: 26,
      assists: 22,
      points: 48,
      plus_minus: '+4',
      time_on_ice_per_game_played: '20:49',
    },
    {
      number: 59,
      name: 'Jake Guentzel',
      born: '10/6/1994',
      league: 'NHL',
      team: 'Tampa Bay Lightning',
      height: 180,
      weight: 80,
      shoots: 'L',
      position: 'C',
      games_played: 55,
      goals: 26,
      assists: 34,
      points: 60,
      plus_minus: '+13',
      time_on_ice_per_game_played: '20:29',
    },
    {
      number: 72,
      name: 'Tage Thompson',
      born: '10/30/1997',
      league: 'NHL',
      team: 'Buffalo Sabres',
      height: 197,
      weight: 100,
      shoots: 'R',
      position: 'C',
      games_played: 57,
      goals: 30,
      assists: 29,
      points: 59,
      plus_minus: '-8',
      time_on_ice_per_game_played: '19:09',
    },
    {
      number: 81,
      name: 'Kyle Connor',
      born: '12/9/1996',
      league: 'NHL',
      team: 'Winnipeg Jets',
      height: 185,
      weight: 83,
      shoots: 'L',
      position: 'LW',
      games_played: 56,
      goals: 25,
      assists: 39,
      points: 64,
      plus_minus: '-3',
      time_on_ice_per_game_played: '21:08',
    },
    {
      number: 86,
      name: 'Jack Hughes',
      born: '5/14/2001',
      league: 'NHL',
      team: 'New Jersey Devils',
      height: 180,
      weight: 80,
      shoots: 'L',
      position: 'C',
      games_played: 36,
      goals: 12,
      assists: 24,
      points: 36,
      plus_minus: '-6',
      time_on_ice_per_game_played: '20:57',
    },
    {
      number: 91,
      name: 'Clayton Keller',
      born: '7/29/1998',
      league: 'NHL',
      team: 'Utah Mammoth',
      height: 178,
      weight: 79,
      shoots: 'L',
      position: 'RW',
      games_played: 57,
      goals: 17,
      assists: 37,
      points: 54,
      plus_minus: '+22',
      time_on_ice_per_game_played: '19:01',
    },
  ],
  defensemen: [
    {
      number: 2,
      name: 'Jackson LaCombe',
      born: '1/9/2001',
      league: 'NHL',
      team: 'Anaheim Ducks',
      height: 188,
      weight: 94,
      shoots: 'L',
      games_played: 56,
      goals: 6,
      assists: 31,
      points: 37,
      plus_minus: '-5',
      time_on_ice_per_game_played: '24:30',
    },
    {
      number: 8,
      name: 'Zach Werenski',
      born: '7/19/1997',
      league: 'NHL',
      team: '7/19/1997',
      height: 188,
      weight: 97,
      shoots: 'L',
      games_played: 52,
      goals: 20,
      assists: 42,
      points: 62,
      plus_minus: '+8',
      time_on_ice_per_game_played: '26:22',
    },
    {
      number: 14,
      name: 'Brock Faber',
      born: '8/22/2002',
      league: 'NHL',
      team: 'Minnesota Wild',
      height: 185,
      weight: 91,
      shoots: 'R',
      games_played: 58,
      goals: 13,
      assists: 24,
      points: 37,
      plus_minus: '+19',
      time_on_ice_per_game_played: '24:59',
    },
    {
      number: 15,
      name: 'Noah Hanifin',
      born: '1/25/1997',
      league: 'NHL',
      team: 'Vegas Golden Knights',
      height: 191,
      weight: 98,
      shoots: 'L',
      games_played: 47,
      goals: 2,
      assists: 18,
      points: 20,
      plus_minus: '-1',
      time_on_ice_per_game_played: '23:26',
    },
    {
      number: 25,
      name: 'Charlie McAvoy',
      born: '12/21/1997',
      league: 'NHL',
      team: 'Boston Bruins',
      height: 185,
      weight: 96,
      shoots: 'R',
      games_played: 45,
      goals: 4,
      assists: 35,
      points: 39,
      plus_minus: '+5',
      time_on_ice_per_game_played: '24:10',
    },
    {
      number: 43,
      name: 'Quinn Hughes',
      born: '10/14/1999',
      league: 'NHL',
      team: 'Minnesota Wild',
      height: 178,
      weight: 82,
      shoots: 'L',
      games_played: 52,
      goals: 5,
      assists: 52,
      points: 57,
      plus_minus: '+9',
      time_on_ice_per_game_played: '28:18',
    },
    {
      number: 74,
      name: 'Jaccob Slavin',
      born: '5/1/1994',
      league: 'NHL',
      team: 'Carolina Hurricanes',
      height: 191,
      weight: 94,
      shoots: 'L',
      games_played: 17,
      goals: 0,
      assists: 3,
      points: 3,
      plus_minus: '+9',
      time_on_ice_per_game_played: '20:12',
    },
    {
      number: 85,
      name: 'Jake Sanderson',
      born: '7/8/2002',
      league: 'NHL',
      team: 'Ottawa Senators',
      height: 188,
      weight: 92,
      shoots: 'L',
      games_played: 57,
      goals: 11,
      assists: 35,
      points: 46,
      plus_minus: '+7',
      time_on_ice_per_game_played: '25:01',
    },
  ],
  goalies: [
    {
      number: 1,
      name: 'Jeremy Swayman',
      born: '11/24/1998',
      league: 'NHL',
      team: 'Boston Bruins',
      height: 191,
      weight: 88,
      games_played: 38,
      wins: 22,
      losses: 12,
      overtime_losses: 3,
      goals_against_average: 2.92,
      save_percentage: 0.903,
      time_on_ice: '2242:38',
    },
    {
      number: 30,
      name: 'Jake Oettinger',
      born: '12/18/1998',
      league: 'NHL',
      team: 'Dallas Stars',
      height: 198,
      weight: 102,
      games_played: 37,
      wins: 23,
      losses: 10,
      overtime_losses: 4,
      goals_against_average: 2.73,
      save_percentage: 0.897,
      time_on_ice: '2195:10',
    },
    {
      number: 37,
      name: 'Connor Hellebuyck',
      born: '5/19/1993',
      league: 'NHL',
      team: 'Winnipeg Jets',
      height: 193,
      weight: 94,
      games_played: 36,
      wins: 13,
      losses: 16,
      overtime_losses: 7,
      goals_against_average: 2.79,
      save_percentage: 0.9,
      time_on_ice: '2152:01',
    },
  ],
};

export const teams: Record<string, Team> = { USA: teamUSA };
